language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
# deploy:
# - provider: s3
#   access_key_id: AKIAIEAMLPHO36E7S73Q
#   secret_access_key: &7199400
#     secure: tASOOMKz7Vi0cCnVgQZBt5F3PZUHrNQ8mXoMj291rMBS+doi9M6Jev1LRrzOl6tpjifO5NgvjiG3G/5zfdaHMJPBX1pSi0QOjfEVfnou8gbFhuCKJp7aWS/7sBXOpcgd0vvnQchn/ph9atGLzWfwrx4BiySiftOy0uBLZ5QNQPe7rxhaRP//wGVnsOWlBZ2QWNXT0XkPCADwKavWCGVbj0pH/VtEm6hXmFCA9CzohnriYOozQXcWHcN+VMDIkZEAhcH0beF2NLGPHlarP1UuwUEv2IrEHCoBtVqjknBgoNrf60BNQtT6IksoD5FrOQKl0KErpAcoZMmDPq8SLrbHjKzLzmB67dJa/+y7s+22vcbwvPjbFDQWUpS4JX6CWX+29sJSzJIMkH2GbeOF2nkr3kiA2SChcZACAT/2dCQSkGtNdSHTdGpe0koh52b58j4A9wNLpwmPDksXYOkoF6Eg5cA2DkI7PnTufCTJuW09GeX3Lvd/Q6rX7+Hs7M3nS4QX+iFwkaVG6CFBEcqS/QA7SWshu2jj9YhqRkdV2EyOvPYSf8Gd1N4cftWrnIT+gcmWtHKluvKV5e1FhN1t5Y/Q1/C34PpbfYhmoM3GusycNmKpKZQRQJGKa3q3RuQECqH9ZuusnxJSpRW/pcmhEwOc8Og4O05lkWAt1GO2vVxJ8vw=
#   local_dir: dpl_cd_upload
#   skip_cleanup: true
#   on: &6923360
#     repo: nbuechler/hungry-interceptor
#     branch: develop
#   bucket: hungry-interceptor-bucket
# - provider: codedeploy
#   access_key_id: AKIAIEAMLPHO36E7S73Q
#   secret_access_key: *7199400
#   bucket: hungry-interceptor-bucket
#   key: latest.zip # This is the zip that goes in s3
#   bundle_type: zip
#   application: hungry-interceptor
#   deployment_group: logro-development-group
#   on: *6923360
# before_deploy:
#   - zip -r latest *
#   - mkdir -p dpl_cd_upload
#   - mv latest.zip dpl_cd_upload/latest.zip
